Revert "clockevents/tcb_clksrc: Prevent disabling an already disabled clock"
This reverts commit b6ea68099f48ed87fc737797eda1295cd04149b1 which is
f02b4b72d12cbae7020a959e2ed0410a464b4cc4 upstream.

It's being reverted due to the build errors is causes:

drivers/clocksource/tcb_clksrc.c:103:8: error:
  implicit declaration of function ‘clockevent_state_detached’;
  did you mean ‘clock_was_set_delayed’?
    [-Werror=implicit-function-declaration]

Signed-off-by: Lee Jones <lee.jones@linaro.org>
Change-Id: I266109b9564516e1487fe42033813b5288ce4f6c